version: '3'
services:

  mongodb:
    image: mongo
    networks:
      - production-network

  node11:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: robertodg/legendas-tv
    container_name: legendas-tv
    ports: 
      - '3000:3000'
    networks:
      - production-network
    depends_on:
      - "mongodb"

networks:
  production-network:
    driver: bridge 
